// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('google-search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('google-search', async function() {
    // Test name: google-search
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.google.es/")
    // 2 | setWindowSize | 843x774 | 
    await driver.manage().window().setRect(843, 774)
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | click | css=#introAgreeButton .RveJvd | 
    await driver.findElement(By.css("#introAgreeButton .RveJvd")).click()
    // 5 | selectFrame | relative=parent | 
    await driver.switchTo().defaultContent()
    // 6 | click | name=q | 
    //await driver.findElement(By.name("q")).click()
    // 7 | type | name=q | selenium
    await driver.findElement(By.name("q")).sendKeys("selenium")
    // 8 | sendKeys | name=q | ${KEY_ENTER}
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    // 9 | click | xpath=//span[contains(.,'Selenium WebDriver')] | 
    //await driver.findElement(By.xpath("//span[contains(.,\'Selenium WebDriver\')]")).click()
  })
})
