// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('imdb-wandavision', function() {
  this.timeout(70000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('imdb-wandavision', async function() {
    // Test name: imdb-wandavision
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.imdb.com/")
    // 2 | setWindowSize | 843x774 | 
    await driver.manage().window().setRect(843, 774)
    // 3 | type | id=suggestion-search | wandavision
    await driver.findElement(By.id("suggestion-search")).sendKeys("wandavision")
    // 4 | sendKeys | id=suggestion-search | ${KEY_ENTER}
    await driver.findElement(By.id("suggestion-search")).sendKeys(Key.ENTER)
    // 5 | click | linkText=TRIVIA | 
    //await driver.findElement(By.linkText("TRIVIA")).click()
  })
})
